[package]
name = "gitt"
version = "0.1.0"
authors = ["Michael Edwards <medwards@walledcity.ca>", "Alvaro Mouriño <alvaro@mourino.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
crossterm = { version = "0.19" }
tui = { version = "0.14", default-features = false, features = ['crossterm'] }
tui-logger = "0.6.3"
log = "0.4"
clap = { version = "3.0.0-beta.2" }
chrono = "0.4.19"
